# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-30 23:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_rm', '0003_auto_20170531_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trash_bin',
            name='path_of_config',
            field=models.CharField(max_length=100),
        ),
    ]
