# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-18 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_rm', '0004_auto_20170531_0200'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegularTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regular_expression', models.CharField(max_length=200)),
                ('start_folder', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='trash_bin',
            name='id',
        ),
        migrations.AlterField(
            model_name='trash_bin',
            name='name',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
