# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-18 20:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smart_rm', '0005_auto_20170618_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='regulartask',
            name='current_trash_bin',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='smart_rm.Trash_bin'),
            preserve_default=False,
        ),
    ]
