# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-18 20:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smart_rm', '0006_regulartask_current_trash_bin'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='current_trash_bin',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='smart_rm.Trash_bin'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='files_to_delete',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
