# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-20 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_rm', '0008_auto_20170620_1228'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='File',
        ),
        migrations.AlterField(
            model_name='task',
            name='files_to_delete',
            field=models.TextField(),
        ),
    ]
