# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-20 21:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smart_rm', '0010_trash_bin_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trash_bin',
            old_name='path_of_config',
            new_name='policies',
        ),
        migrations.RemoveField(
            model_name='trash_bin',
            name='path_of_database',
        ),
    ]
