# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-22 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_rm', '0013_auto_20170622_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='state',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
