# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-22 23:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_rm', '0016_auto_20170622_2345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='files_to_delete',
            new_name='files',
        ),
        migrations.AddField(
            model_name='task',
            name='name_of_operation',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
