# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-23 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_rm', '0019_auto_20170623_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='name_of_operation',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
